development:
  password: shptka_93784a65109d693a090f486c0867d5eb
  theme_id: "123873001527"
  store: syltbar.myshopify.com
  ignore_files:
    # - config/settings_data.json
    # - config/settings_schema.json

    # 122347683895 live
